//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaBodegaG1.BodegasWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/bodegaCPWSSOAP.Dominio")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodCliente {
            get {
                return this.CodClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.CodClienteField, value) != true)) {
                    this.CodClienteField = value;
                    this.RaisePropertyChanged("CodCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUser {
            get {
                return this.IdUserField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUserField, value) != true)) {
                    this.IdUserField = value;
                    this.RaisePropertyChanged("IdUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCliente {
            get {
                return this.NombreClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreClienteField, value) != true)) {
                    this.NombreClienteField = value;
                    this.RaisePropertyChanged("NombreCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Referencia {
            get {
                return this.ReferenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenciaField, value) != true)) {
                    this.ReferenciaField = value;
                    this.RaisePropertyChanged("Referencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErroresException", Namespace="http://schemas.datacontract.org/2004/07/bodegaCPWSSOAP.Errores")]
    [System.SerializableAttribute()]
    public partial class ErroresException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bodega", Namespace="http://schemas.datacontract.org/2004/07/bodegaCPWSSOAP.Dominio")]
    [System.SerializableAttribute()]
    public partial class Bodega : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdBodegaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUserBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contacto {
            get {
                return this.ContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactoField, value) != true)) {
                    this.ContactoField = value;
                    this.RaisePropertyChanged("Contacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdBodega {
            get {
                return this.IdBodegaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdBodegaField, value) != true)) {
                    this.IdBodegaField = value;
                    this.RaisePropertyChanged("IdBodega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUserB {
            get {
                return this.IdUserBField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUserBField, value) != true)) {
                    this.IdUserBField = value;
                    this.RaisePropertyChanged("IdUserB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitud {
            get {
                return this.LatitudField;
            }
            set {
                if ((this.LatitudField.Equals(value) != true)) {
                    this.LatitudField = value;
                    this.RaisePropertyChanged("Latitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitud {
            get {
                return this.LongitudField;
            }
            set {
                if ((this.LongitudField.Equals(value) != true)) {
                    this.LongitudField = value;
                    this.RaisePropertyChanged("Longitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BodegasWS.IBodegaBCService")]
    public interface IBodegaBCService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBodegaBCService/CrearCliente", ReplyAction="http://tempuri.org/IBodegaBCService/CrearClienteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SistemaBodegaG1.BodegasWS.ErroresException), Action="http://tempuri.org/IBodegaBCService/CrearClienteErroresExceptionFault", Name="ErroresException", Namespace="http://schemas.datacontract.org/2004/07/bodegaCPWSSOAP.Errores")]
        SistemaBodegaG1.BodegasWS.Cliente CrearCliente(SistemaBodegaG1.BodegasWS.Cliente clienteACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBodegaBCService/CrearCliente", ReplyAction="http://tempuri.org/IBodegaBCService/CrearClienteResponse")]
        System.Threading.Tasks.Task<SistemaBodegaG1.BodegasWS.Cliente> CrearClienteAsync(SistemaBodegaG1.BodegasWS.Cliente clienteACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBodegaBCService/ObtenerCliente", ReplyAction="http://tempuri.org/IBodegaBCService/ObtenerClienteResponse")]
        SistemaBodegaG1.BodegasWS.Cliente ObtenerCliente(string codCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBodegaBCService/ObtenerCliente", ReplyAction="http://tempuri.org/IBodegaBCService/ObtenerClienteResponse")]
        System.Threading.Tasks.Task<SistemaBodegaG1.BodegasWS.Cliente> ObtenerClienteAsync(string codCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBodegaBCService/Modificarcliente", ReplyAction="http://tempuri.org/IBodegaBCService/ModificarclienteResponse")]
        SistemaBodegaG1.BodegasWS.Cliente Modificarcliente(SistemaBodegaG1.BodegasWS.Cliente clienteAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBodegaBCService/Modificarcliente", ReplyAction="http://tempuri.org/IBodegaBCService/ModificarclienteResponse")]
        System.Threading.Tasks.Task<SistemaBodegaG1.BodegasWS.Cliente> ModificarclienteAsync(SistemaBodegaG1.BodegasWS.Cliente clienteAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBodegaBCService/ObtenerBodega", ReplyAction="http://tempuri.org/IBodegaBCService/ObtenerBodegaResponse")]
        SistemaBodegaG1.BodegasWS.Bodega ObtenerBodega(string codBodega);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBodegaBCService/ObtenerBodega", ReplyAction="http://tempuri.org/IBodegaBCService/ObtenerBodegaResponse")]
        System.Threading.Tasks.Task<SistemaBodegaG1.BodegasWS.Bodega> ObtenerBodegaAsync(string codBodega);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBodegaBCService/ListarBodegas", ReplyAction="http://tempuri.org/IBodegaBCService/ListarBodegasResponse")]
        SistemaBodegaG1.BodegasWS.Bodega[] ListarBodegas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBodegaBCService/ListarBodegas", ReplyAction="http://tempuri.org/IBodegaBCService/ListarBodegasResponse")]
        System.Threading.Tasks.Task<SistemaBodegaG1.BodegasWS.Bodega[]> ListarBodegasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBodegaBCServiceChannel : SistemaBodegaG1.BodegasWS.IBodegaBCService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BodegaBCServiceClient : System.ServiceModel.ClientBase<SistemaBodegaG1.BodegasWS.IBodegaBCService>, SistemaBodegaG1.BodegasWS.IBodegaBCService {
        
        public BodegaBCServiceClient() {
        }
        
        public BodegaBCServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BodegaBCServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BodegaBCServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BodegaBCServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SistemaBodegaG1.BodegasWS.Cliente CrearCliente(SistemaBodegaG1.BodegasWS.Cliente clienteACrear) {
            return base.Channel.CrearCliente(clienteACrear);
        }
        
        public System.Threading.Tasks.Task<SistemaBodegaG1.BodegasWS.Cliente> CrearClienteAsync(SistemaBodegaG1.BodegasWS.Cliente clienteACrear) {
            return base.Channel.CrearClienteAsync(clienteACrear);
        }
        
        public SistemaBodegaG1.BodegasWS.Cliente ObtenerCliente(string codCliente) {
            return base.Channel.ObtenerCliente(codCliente);
        }
        
        public System.Threading.Tasks.Task<SistemaBodegaG1.BodegasWS.Cliente> ObtenerClienteAsync(string codCliente) {
            return base.Channel.ObtenerClienteAsync(codCliente);
        }
        
        public SistemaBodegaG1.BodegasWS.Cliente Modificarcliente(SistemaBodegaG1.BodegasWS.Cliente clienteAModificar) {
            return base.Channel.Modificarcliente(clienteAModificar);
        }
        
        public System.Threading.Tasks.Task<SistemaBodegaG1.BodegasWS.Cliente> ModificarclienteAsync(SistemaBodegaG1.BodegasWS.Cliente clienteAModificar) {
            return base.Channel.ModificarclienteAsync(clienteAModificar);
        }
        
        public SistemaBodegaG1.BodegasWS.Bodega ObtenerBodega(string codBodega) {
            return base.Channel.ObtenerBodega(codBodega);
        }
        
        public System.Threading.Tasks.Task<SistemaBodegaG1.BodegasWS.Bodega> ObtenerBodegaAsync(string codBodega) {
            return base.Channel.ObtenerBodegaAsync(codBodega);
        }
        
        public SistemaBodegaG1.BodegasWS.Bodega[] ListarBodegas() {
            return base.Channel.ListarBodegas();
        }
        
        public System.Threading.Tasks.Task<SistemaBodegaG1.BodegasWS.Bodega[]> ListarBodegasAsync() {
            return base.Channel.ListarBodegasAsync();
        }
    }
}
